name: Build libfp - Windows
on:
  workflow_call:
    secrets:
      qt_ffynnon_cred:
        description: 'Credentials for getting Qt from Ffynnon'
        required: true
env:
  qt_install_dir: ${{ github.workspace }}/Qt/Install
  libfp_src_suffix: libfp/Source
  libfp_src_dir: ${{ github.workspace }}/libfp/Source
  libfp_build_dir: ${{ github.workspace }}/libfp/Build

jobs:
  build-libfp:
    name: Build libfp - Windows (Debug/Release)
    strategy:
      fail-fast: false
      matrix:
        lib_linkage: [shared, static]
        include:
          - lib_linkage: shared
            cmake_bsl: ON
          - lib_linkage: static
            cmake_bsl: OFF
    runs-on: windows-latest
    env:
      vs_dev_dir: C:/Program Files/Microsoft Visual Studio/2022/Enterprise
      cmake_gen: Ninja Multi-Config
    steps:
    - name: Set derived variables with shell because GitHub Actions env context sucks
      run: |
        echo "libfp_package_path=${{ env.libfp_build_dir }}/out/dist" >> $Env:GITHUB_ENV
        $libfp_install_path="${{ env.libfp_build_dir }}/out/install"
        echo "libfp_install_path=$libfp_install_path" >> $Env:GITHUB_ENV
        echo "qt_cmake=${Env:qt_install_dir}/bin/qt-cmake.bat" >> $Env:GITHUB_ENV
    - name: Install Qt (custom build)
      uses: oblivioncth/actions/general/install-and-cache-qt-from-ffynnon@dev
      with:
        version: 6.4.2
        os: windows
        compiler: msvc2022
        linkage: ${{ matrix.lib_linkage }}
        path: ${{ env.qt_install_dir }}
        credentials: ${{ secrets.qt_ffynnon_cred }}
    - name: Checkout libfp
      uses: actions/checkout@v3
      with:
        path: ${{ env.libfp_src_suffix }}
        fetch-depth: 0 # Required for verbose versioning to work correctly
    - name: Build/Install libfp
      working-directory: ${{ env.libfp_src_dir }}
      shell: cmd
      run: |
        echo Setup C++ Build Environment...
        CALL "${{ env.vs_dev_dir }}\Common7\Tools\VsDevCmd.bat" -arch=amd64
        echo Configure CMake using Qt wrapper...
        CALL "${{ env.qt_cmake }}" -G "${{ env.cmake_gen }}" -S "${{ env.libfp_src_dir}}" -B "${{ env.libfp_build_dir }}" -D BUILD_SHARED_LIBS=${{ matrix.cmake_bsl }}"  
        echo "Changing to build directory..."
        cd "%libfp_build_dir%"
        echo "Building libfp debug..."
        cmake --build . --target all --config Debug
        echo "Building libfp release..."
        cmake --build . --target all --config Release
        echo "Installing libfp Debug"
        cmake --install . --config Debug
        echo "Installing libfp Release..."
        cmake --install . --config Release
        echo "Packaging libfp..."
        cpack -C "Debug;Release"
        echo "Build complete."
    - name: Get libfp artifact name
      run: |
        $artifact_name=$((Get-ChildItem -Path "${{ env.libfp_package_path }}" -Filter *.zip)[0].BaseName)
        echo "current_artifact_name=$artifact_name" >> $Env:GITHUB_ENV
    - name: Upload libfp build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.current_artifact_name }}
        path: ${{ env.libfp_install_path }}
        if-no-files-found: error
