name: libfp Push Reaction
on:
  workflow_dispatch:
  push:
    branches-ignore:
    - 'master'

jobs:
  trigger-windows-build:
    name: Build libfp (Windows)
    uses: ./.github/workflows/build-libfp-windows.yml
    secrets:
      qt_ffynnon_cred: ${{ secrets.OBYBOT_FFYNNON_CREDS }}

  trigger-linux-build:
    name: Build libfp (Linux)
    uses: ./.github/workflows/build-libfp-linux.yml
    secrets:
      qt_ffynnon_cred: ${{ secrets.OBYBOT_FFYNNON_CREDS }}
